### PR TITLE
js code generator

### PR DESCRIPTION
**Pull request by killanch**
first cut of javascript code generator - generates the model classes based on specifications

### CODE REVIEW

**Comment by killanch** [comment]
@natabal pls review

**Comment by pdellaert** [comment]
@killanch Just for my understanding, can you summarise the capabilities of this initial version? 
As i understand from the current code, it just creates the base entities with its properties, but no reference to children or relations, correct? Also missing the session object or root object to start the connection towards VSD.

(Want to understand the status :))

Thanks!

**Comment by killanch** [comment]
@pdellaert yes, it just creates the base entities. similar to,
https://github.mv.usa.alcatel.com/Architect/vsd-react-ui/blob/master/src/lib/models/NULocation.js

**Comment by killanch** [comment]
@natabal addressed alignment, and other es-lint reported errors in generated file. pls merge PR.

**Comment by killanch** [comment]
@natabal pls find sample file generated.
Since github wasn't allowing .js extension file to be attached, Ive renamed the file with .txt extension

[NUEnterprise.txt](https://github.com/nuagenetworks/monolithe/files/1086485/NUEnterprise.txt)

**Pull request merged**
