### PR TITLE
Added missing 'python' directory under examples/vanilla/sdk for prope…

### PR DESCRIPTION
**Pull request by martin-leclerc**
…r Python code generation of tdldk using monolithe.

### CODE REVIEW

**Comment by primalmotion** [comment]
Wow, I completely missed the notification about this PR. Sorry about that.
I think I fixed the issue today, but thanks anyway :)

**Comment by martin-leclerc** [comment]
Hi Antoine,

 

No worries, I just wanted to make an early contribution to the Monolithe project J

 

I am planning to submit the first version of the java plug-in (code generator) for Monolithe next Thursday (March 10). I have also written a java version of the sample program (originally in Python, the one located under monolithe\examples). 

 

Do you have a suggestion as to where I could put the (Java) source code of the sample program along with the Maven script to build it?

 

Thanks,

 

Martin.

**Comment by primalmotion** [comment]
Do you plan to create an external plugin or to embed it in the monolithe's internal lang package (like Go, Python and HTML)?

**Comment by martin-leclerc** [comment]
The code for the java code generation is currently embedded in the Monolithe codebase, the main reason being that I started working on it week ago (i.e. prior to the introduction of the plug-in framework). 

 

Would you rather suggest packaging it up as a separate plug-in?

 

Martin.

**Pull request closed without merging**
